Robots:
  cf4:
      type : 'cf21'
      size : 'small'
      m    : 0.034
      I    : [16.571710e-6, 16.655602e-6, 29.261652e-6]
      d    : 0.046 #4e-3
      cft  : 0.006 #0.005964552 
      drag : 0 # 0: do not include drag model, 1: include simple drag model
      mxTh : 12.0  #maximum thrust in [g] per motor
      refTrajPath : 'trajectoriescsv/figure8.csv' # Path of the reference trajectory
      controller  : 
        name: 'lee_firmware' # lee_firmware # lee, sjc
        kpx  : 9.0 
        kpy  : 9.0
        kpz  : 9.0
        kdx  : 7.0
        kdy  : 7.0
        kdz  : 7.0
        kipx : 5.0
        kipy : 5.0
        kipz : 5.0
        krx  : 0.0055 
        kry  : 0.0055 
        krz  : 0.0055 
        kwx  : 0.0013
        kwy  : 0.0013
        kwz  : 0.0013
        kix  : 0.012
        kiy  : 0.018
        kiz  : 0.015

      initConditions : 
        init_pos_Q      : [0,  0,  0] # circleTraj1: [0.91321, 0.240792, 0.699988] # [0, 0, 0.7] #0.216917, 0.417135, 0.700008] #[0.090768, 0.234859, 0.397903] #[0.207449, 0.228759, -0.142567]
        init_attitude_Q : [0,  0,  0] 
        init_linVel_Q   : [0,  0,  0]
        init_angVel_Q   : [0,  0,  0]
      
      payload :  
        mode  : 'disabled'
        m_p   : 0.01 # Mass payload [kg]
        l_c   : 0.3 # Length of cable [m]
        ## INITIAL CONDITIONS FOR PAYLOAD
        init_pos_L  :  [0,  0,  -0.3] #[0.91321, 0.240792,-0.800012] #[0.91321, 0.240792, -0.3]
        init_linV_L :  [0,   0,    0]
        p           :  [0,   0,   -1] # Initial condition for directional unit vector from UAV to payload
                                                      # p = [0,0,-1]
                                    # pointing downwards expressed in Inertial Frame
        wl          :  [0,   0,    0] # Angular velocity of payload 
  # cf3: 
  #   type : 'cf_custom'
  #   size : 'big'
  #   m    : 4.34
  #   I    : [0.0820, 0.0845, 0.1377]
  #   d    : 0.315
  #   cft  : 0.0008004  
  #   drag : 0 # 0: do not include drag model, 1: include simple drag model
  #   mxTh : 12000.0  #maximum thrust in [g] per motor
  #   refTrajPath : 'trajectoriescsv/hover_01.csv' # Path of the reference trajectory
  #   controller  : 
  #           name: 'sjc' # lee_firmware # lee, sjc
  #           kpx  : 9.0 #10  
  #           kpy  : 9.0
  #           kpz  : 9.0
  #           kdx  : 7.0
  #           kdy  : 7.0
  #           kdz  : 7.0
  #           kipx : 5.0
  #           kipy : 5.0
  #           kipz : 5.0
  #           krx  : 0.0055 
  #           kry  : 0.0055 
  #           krz  : 0.0055 
  #           kwx  : 0.0013
  #           kwy  : 0.0013
  #           kwz  : 0.0013
  #           kix  : 0.012
  #           kiy  : 0.018
  #           kiz  : 0.015
  #   initConditions : 
  #     init_pos_Q      : [-1, 0, 0] #[0.090768, 0.234859, 0.397903] #[0.207449, 0.228759, -0.142567] 
  #     init_attitude_Q : [0,  0,  0] 
  #     init_linVel_Q   : [0,  0,  0]
  #     init_angVel_Q   : [0,  0,  0]
    
  #   payload :  
  #     mode  : 'enabled'
  #     m_p   : 0.01 # Mass payload [kg]
  #     l_c   : 0.3 # Length of cable [m]
  #     ## INITIAL CONDITIONS FOR PAYLOAD
  #     init_pos_L  :  [-1,  0, -0.3] #[0.090768, 0.234859, 0.097903] #[0.91321, 0.240792, -0.3]
  #     init_linV_L :  [0,   0,    0]
  #     p           :  [0,   0,   -1] # Initial condition for directional unit vector from UAV to payload
  #                                                   # p = [0,0,-1]
  #                                 # pointing downwards expressed in Inertial Frame
  #     wl          :  [0,   0,   0] # Angular velocity of payload
  

RobotswithPayload:
  payload:
    mode        : 'shared' # shared: payload is shared between UAVs through cables,  otherwise: independent paylaod for each UAV
    m_p         : 0.01
    inertia    :  [0, 0, 0] #[0.001072, 0.001072, 0.001072] # [0.001072, 0.001072, 0.001072] # [0.001072, 0.001072, 0.001072] #[0.001072, 0.001072, 0.001072] # sphere rigid body of radius = 0.5176 [m], mass = 0.01 [kg], Ixx = Iyy = Izz = (2/5) * m * r^2 
    init_pos_L  : [0, 0, 0.4] #[0.055238, 0, 0]
    #[0.747886, 0.573861, 0] #[0.747886, 0.573861, 0] #[0, 0, -0.3] #[0.747886, 0.573861, 0] #[0.747886, 0.573861, 0] #[0.91321, 0.240792, 0.699988] #[0.000094,0,0] #[0.91321, 0.240792, 0.699988] # [0,0.000094,0] #[0.91321, 0.240792, 0.699988] # [0.090768, 0.234859, 0.097903] #[0.91321, 0.240792,-0.800012]
    init_linV_L : [0,   0,    0]
    init_angle  : [0,   0,    0]
    wl          : [0,   0,    0]
    refTrajPath: 'trajectoriescsv/hover_01.csv' #linTraj_traj.csv #cirTraj1.csv
    payloadCtrl:
      name: 'lee_firmware'
      payloadLead: 'enabled'
      optimize:
        mode: 'enabled'
        qp  : 'osqp'
        downwashAware: true
      offset: [0.0, 0.0, 0.0]
      gains:
        ctrlLee:
          # Payload PID
          kpx  : 15.0 #18.0 #10.0 #10.0  
          kpy  : 15.0 #18.0 #10.0 #10.0
          kpz  : 15.0 #18.0 #10.0 #10.0
          kdx  : 12.5 #4.0 #16.0 #8.0 #8.0
          kdy  : 12.5 #4.0 #16.0 #8.0 #8.0
          kdz  : 12.5 #4.0 #16.0 #8.0 #8.0
          kipx :  0.0
          kipy :  0.0
          kipz :  0.0
          # Payload PID Attitude 
          krpx  : 0.01 # 0.00002
          krpy  : 0.01 # 0.00002 
          krpz  : 0.01 # 0.00002
          kwpx  : 0.005 #0.00001
          kwpy  : 0.005 #0.00001
          kwpz  : 0.005 #0.00001
          # UAV PID Attitude  
          krx  : 0.008
          kry  : 0.008
          krz  : 0.008 
          kwx  : 0.0013
          kwy  : 0.0013
          kwz  : 0.0013
          kix  : 0.0 #0.012
          kiy  : 0.0 #0.018
          kiz  : 0.0 #0.015     
        cable:
          # Cable PD
          kqx  : 14.0 #25.0 #10.0 #25.0 #35.0 #3.0 #10.0 #30.0 #25.0 
          kqy  : 14.0 #25.0 #10.0 #25.0 #35.0 #3.0 #10.0 #30.0 #25.0 
          kqz  : 14.0 #25.0 #10.0 #25.0 #35.0 #3.0 #10.0 #30.0 #25.0 
          kwcx : 12.0 #12.0 #24.0 #22.0 #34.0 #1.0 #28.0 #24.0  
          kwcy : 12.0 #12.0 #24.0 #22.0 #34.0 #1.0 #28.0 #24.0  
          kwcz : 12.0 #12.0 #24.0 #22.0 #34.0 #1.0 #28.0 #24.0  
  Robots:
    cf4: 
      type : 'cf21'
      size : 'small'
      m    : 0.034
      I    : [16.571710e-6, 16.655602e-6, 29.261652e-6]
      d    : 0.046
      cft  : 0.006 #0.005964552 
      drag : 0 # 0: do not include drag model, 1: include simple drag model
      mxTh : 12000.0  #maximum thrust in [g] per motor
      refTrajPath  : ' ' #'trajectoriescsv/figure8.csv' 
      controller  : 
        name: 'lee' # lee_firmware # lee, sjc
        kpx  : 9.0 #10  
        kpy  : 9.0
        kpz  : 9.0
        kdx  : 7.0
        kdy  : 7.0
        kdz  : 7.0
        kipx : 5.0
        kipy : 5.0
        kipz : 5.0
        krx  : 0.0055 
        kry  : 0.0055 
        krz  : 0.0055 
        kwx  : 0.0013
        kwy  : 0.0013
        kwz  : 0.0013
        kix  : 0.012
        kiy  : 0.018
        kiz  : 0.015     
      l_c  :  0.8 #0.854 #0.77 # Length of cable
      q_dg : [30, 0, 180] #[0,-51.4298,0]   #[-39.8273,36.159552, 20.156] #[-45, 0, 0] #[-45, 0, 0] # [0, 0, 0]  # Initial angle between UAV and payload
      qd   : [0, 0, 0]  # Initial angle derivates between UAV and payload (i.e., of cables)
      pos_fr_payload: [0.2241, 0.1294, 0] #[0.2588, 0, 0] #position vector of the cable on the load (i.e., zero vector means a point mass)
      initConditions:
        init_pos_Q      : [0,  0, 0] #[0.91321, 0.240792, 0.7]
        init_attitude_Q : [0,  0, 0] 
        init_linVel_Q   : [0,  0, 0]
        init_angVel_Q   : [0,  0, 0]
      NumOfHplane: 2
      hyperplanes: # each plane is defined with an 'angle' and 'heading'. Similar to the definition of the generation of the rotation matrices
        rpy:  [[20, 0, 0],
               [35, 0, 0]] #[30, 0, 180] # the RPY of the z-axis of the plane(s)
        yaw: [[180],
              [0]] #[180] #the 'yaw' x-axis of the plane(s)
        
    cf5: 
      type : 'cf21'
      size : 'small'
      m    : 0.034
      I    : [16.571710e-6, 16.655602e-6, 29.261652e-6]
      d    : 0.046
      cft  : 0.006 #0.005964552 
      drag : 0 # 0: do not include drag model, 1: include simple drag model
      mxTh : 12000.0  # Maximum thrust in [g] per motor
      refTrajPath  : ' ' #'trajectoriescsv/figure8.csv' 
      controller  : 
        name: 'lee_firmware' # lee_firmware # lee, sjc
        kpx  : 15.0 #10  
        kpy  : 15.0
        kpz  : 15.0
        kdx  : 12.5.0
        kdy  : 12.5.0
        kdz  : 12.5.0
        kipx : 0.0
        kipy : 0.0
        kipz : 0.0
        krx  : 0.008 
        kry  : 0.008 
        krz  : 0.008 
        kwx  : 0.0013
        kwy  : 0.0013
        kwz  : 0.0013
        kix  : 0.02
        kiy  : 0.02
        kiz  : 0.02     
      l_c  : 0.8 #0.754 #0.707 # Length of cable
      q_dg : [30, 0, 300]  # [0, 0, 0]  # Initial angle between UAV and payload
      qd   : [0, 0, 0]  # Initial angle derivates between UAV and payload (i.e., of cables)
      pos_fr_payload: [0.2241, -0.1294, 0] #[-0.1294, 0.2241, 0] #position vector of the cable on the load (i.e., zero vector means a point mass)
      initConditions:
        init_pos_Q      : [0,  0, 0] #[0.91321, 0.240792, 0.7]
        init_attitude_Q : [0,  0, 0] 
        init_linVel_Q   : [0,  0, 0]
        init_angVel_Q   : [0,  0, 0]
      NumOfHplane: 2
      hyperplanes: 
        rpy: [[20, 0, 120],
              [35, 0, 120]] #[30,0,0]
        yaw: [[300],
             [120]]  #[0]

    cf6: 
      type : 'cf21'
      size : 'small'
      m    : 0.034
      I    : [16.571710e-6, 16.655602e-6, 29.261652e-6]
      d    : 0.046
      cft  : 0.006 #0.005964552 
      drag : 0 # 0: do not include drag model, 1: include simple drag model
      mxTh : 12000.0  # Maximum thrust in [g] per motor
      refTrajPath  : ' ' #'trajectoriescsv/figure8.csv' 
      controller  : 
        name: 'lee_firmware' # lee_firmware # lee, sjc
        kpx  : 15.0 #10  
        kpy  : 15.0
        kpz  : 15.0
        kdx  : 12.5.0
        kdy  : 12.5.0
        kdz  : 12.5.0
        kipx : 0.0
        kipy : 0.0
        kipz : 0.0
        krx  : 0.008 
        kry  : 0.008 
        krz  : 0.008 
        kwx  : 0.0013
        kwy  : 0.0013
        kwz  : 0.0013
        kix  : 0.02
        kiy  : 0.02
        kiz  : 0.02     
      l_c  : 0.8 #0.754 #0.707 # Length of cable
      q_dg : [30, 0, 420]  # [0, 0, 0]  # Initial angle between UAV and payload
      qd   : [0, 0, 0]  # Initial angle derivates between UAV and payload (i.e., of cables)
      pos_fr_payload: [0.2241, -0.1294, 0] #[-0.1294, 0.2241, 0] #position vector of the cable on the load (i.e., zero vector means a point mass)
      initConditions:
        init_pos_Q      : [0,  0, 0] #[0.91321, 0.240792, 0.7]
        init_attitude_Q : [0,  0, 0] 
        init_linVel_Q   : [0,  0, 0]
        init_angVel_Q   : [0,  0, 0]
      NumOfHplane: 2
      hyperplanes: 
        rpy: [[20, 0, 120],
              [35, 0, 120]] #[30,0,0]
        yaw: [[300],
             [120]]  #[0]
  
environment:
  floor:  
    mode: False
    Kp: [0,0,0]
    Kd: [0,0,0]
## Simulation parameters 
dt : 1e-3 # time step
simtime: 2.022e3 #  This is added (or subtracted) from the total trajectory time defined in the csv file
sample: 250 #frames per second
